#!/bin/bash
#SBATCH --job-name=grid-search
#SBATCH --account=project_2000539
#SBATCH --time=60:00:00
#SBATCH --mem-per-cpu=20G
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1

module load pytorch

source /scratch/project_2005072/cassandra/.venv/bin/activate

export OLLAMA_MODELS=/scratch/project_2005072/cassandra/.cache/
export TMPDIR=/scratch/project_2005072/cassandra/.cache/

/scratch/project_2005072/cassandra/ollama-test/bin/ollama serve&

python3.9 ../gridsearch.py --model $1 --input_file /scratch/project_2005072/cassandra/ocr-postcorrection-data/English/FULL_DOCUMENTS/en_test_full.jsonl.gz --output_file $1_on_tcp_60h.jsonl

seff $SLURM_JOB_ID