#!/bin/bash
#SBATCH --account=project_2005072
#SBATCH --time=02:30:00
#SBATCH --partition=gpu

module load pytorch

source /scratch/project_2005072/cassandra/.venv/bin/activate

export OLLAMA_MODELS=/scratch/project_2005072/cassandra/.cache/
export TMPDIR=/scratch/project_2005072/cassandra/.tmp/
export OLLAMA_KEEP_ALIVE=120m

echo $SLURM_JOB_ID

/scratch/project_2005072/cassandra/ollama-test/bin/ollama serve&

sleep 30

if [ "$4" == "fi" ]; then
    temperature=0.14
    top_k=30
    top_p=0.60
elif [ "$4" == "en" ]; then
    temperature=0.26
    top_k=65
    top_p=0.66
else
    echo "Unknown language option: $4"
    exit 1
fi
python3.9 ../produce_correction.py --model $1 --input_file $2 --output_file ../quantization_output/$1$3_$4_test.jsonl --quantization "$3" --temperature $temperature --top_k $top_k --top_p $top_p

seff $SLURM_JOB_ID