#!/bin/bash

mkdir -p eo_len

for i in "mistralai/Mixtral-8x7B-Instruct-v0.1" #"google/gemma-2-27b-it" "mistralai/Mixtral-8x7B-Instruct-v0.1" "meta-llama/Meta-Llama-3.1-8B-Instruct" "meta-llama/Meta-Llama-3-8B-Instruct" "google/gemma-2-9b-it"
do
    for j in 100 #100 200 300
    do
        for k in Finnish  #English #Finnish  
        do
            if [[ $k == *"English"* ]]; then
                lang="en"
            elif [[ $k == *"Finnish"* ]]; then
                lang="fin"
            fi

            hours=4
            case $i in
                "meta-llama/Meta-Llama-3.1-70B-Instruct"|"mistralai/Mixtral-8x7B-Instruct-v0.1") mem_per_cpu=90; hours=4;;
                "google/gemma-2-27b-it") mem_per_cpu=40; hours=4;;  
                *) mem_per_cpu=20
            esac
            
            num_gpus=$((mem_per_cpu / 32))    
            if (( num_gpus < 1 )); then
                num_gpus=1
            elif (( num_gpus > 4 )); then
                num_gpus=4
            fi
    
            sbatch --job-name len_${i}_${j}_${lang} \
                   --mem-per-cpu=${mem_per_cpu}G \
                   --time=0${hours}:00:00 \
                   --gres=gpu:v100:${num_gpus} \
                   -e eo_len/${i}_${j}_${lang}.err \
                   -o eo_len/${i}_${j}_${lang}.out \
                   length.script $i $j $lang
        done
    done
done
