#!/bin/bash

mkdir -p eo_quantization

for i in "meta-llama/Meta-Llama-3.1-8B-Instruct" "meta-llama/Meta-Llama-3-8B-Instruct" "mistralai/Mixtral-8x7B-Instruct-v0.1"
do
    for j in "/scratch/project_2005072/cassandra/ocr-postcorrection-data/Finnish/FULL_DOCUMENTS/ABBYY_old/Batched/fin_test_sample200.jsonl" #"/scratch/project_2005072/cassandra/ocr-postcorrection-data/English/SEGMENTED_DOCUMENTS/en_test_sample200.jsonl" 
    do
        hours=3

        if [[ $j == *"English"* ]]; then
            lang="en"
        elif [[ $j == *"Finnish"* ]]; then
            lang="fi"
        fi

        for quant in "fp16" 
        do
            mem_per_gpu=32
            
            num_gpus=1

             
            case $i in
                "meta-llama/Meta-Llama-3.1-70B-Instruct") num_gpus=4; hours=6;;
                "mistralai/Mixtral-8x7B-Instruct-v0.1") num_gpus=4; mem_per_gpu=32; hours=4;;  
                "google/gemma-2-27b-it") num_gpus=4; mem_per_gpu=18; hours=4;;  
                "google/gemma-2-9b-it"|"meta-llama/Meta-Llama-3-8B-Instruct"|"meta-llama/Meta-Llama-3.1-8B-Instruct") num_gpus=1;;
                *) num_gpus=1
            esac

            sbatch --job-name test_${i}${quant}_${lang} \
                   --time=0${hours}:00:00 \
                   --mem-per-gpu=${mem_per_gpu}G \
                   --gres=gpu:v100:${num_gpus} \
                   -e eo_quantization/${i}${quant}_${lang}_test.err \
                   -o eo_quantization/${i}${quant}_${lang}_test.out \
                   quantization.script $i $j $quant $lang
        done
    done
done
